spring:
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          zk-nodes: 10.9.3.22:2181
          brokers: 10.9.3.22:19092
          configuration:
            auto:
              offset:
                reset: latest
server:
  port: 12150
endpoints:
  restart:
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.9.3.19:11010/eureka/
  instance:
    preferIpAddress: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
management:
  security:
    enabled: false
test:
  name: tianqi
